[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
venvPath = "."
venv = ".venv"

[project]
name = "umap-cam"
version = "0.1"
dependencies = ["jax[cuda12]"]

[project.optional-dependencies]
test = ["scikit-learn", "matplotlib"]
